--CREATE DATABASE AzMB101_Jafar_AdoNet_ORM

USE AzMB101_Jafar_AdoNet_ORM

--DROP TABLE Blogs
--DROP TABLE Users

CREATE TABLE Users(
	ID INT IDENTITY PRIMARY KEY,
	[Name] NVARCHAR(31),
	Surname NVARCHAR(31),
	Username VARCHAR(31) UNIQUE,
	[Password] NVARCHAR(256) NOT NULL
)

CREATE TABLE Blogs(
	ID INT IDENTITY PRIMARY KEY,
	Title NVARCHAR(31),
	Describtion NVARCHAR(63),
	[User_ID] INT FOREIGN KEY REFERENCES Users(ID)
)
